#CI De Nível 03 - Disparo automaticos sempre que outro for concluido, como deploy

# Nome que vai aparecer la nas opções de pipe
name: 'Execução por deploy'

# Triggers ou gatilhos de execução
  #gatilho de exec manual = workflow_run

on:
  workflow_run:
    workflows: ['Execução Manual']

jobs:

  # descricao do job
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    # passo a passo das acoes do job
    steps:

      - uses: actions/checkout@v4

   # - uses: actions/setup-node@v4
   #   with:
   #     node-version:çts/*
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando depedências
        run: yarn
    
      - name: Instalando Playwright
        run: yarn playwright install
    
      - name: Testes E2E (end-to-end)
        run: yarn run e2e
      #passed, failed, cancellad
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report